<?php
return [
    'You are a field in my class. You will always be protected.',
    'Are you an exception? Let me catch you.',
    'You are my increment operator. You make my value increase.',
    'I think you’re my compiler. My life wouldn’t start without you.',
    'You are my initializer: without you, my life would point to nothing (null).',
    'I am a BufferedReader. You input meaning into my life.',
    'You are my semicolon; always present in everything I do.',
    'You are the JDK (Java Development Kit) in my life. I won’t compile without you.',
    'If I were a method, you must be my parameter, because I will always need you.',
    'Can you be my private variable? I want to be the only one with access to you.',
    'We are an aggregation of classes: one cannot exist without the other.',
    'public class YourWorld extends MyWorld',
    'My love is a for loop without the increment operator— infinitive,  non-terminating, and dificult to stop once it starts running.',
    'Let me be the ‘throws Exception’ to your ‘public static void main (String[] args)’. I will accept whatever you give me.',
    '[me != me]. [me += you].',
    'You are my superclass: you define what I can do.',
    'You are the IDE of my life: I find it easier because of you.',
    'My main method is ‘public love iLoveYou().’',
    'I am the field attribute in your class: I can’t exist unless you do.',
    'My love for you is a constant variable: unupdatable and unchangeable.',
    'Are you an applet? You make me feel all GUI (gooey) inside.',
    'You are my loop condition. I keep coming back to you.',
    'You are my methods. I am nothing without you.',
    'Are you my driver? Because you make my life worthwhile.',
    'You are my API. I want to know everything about you.',
    'Can you be my ActionListener? That way you notice everything that I do.',
    'I am a boolean method whose love will always return true.',
    'My love for you comes with no strings attached.',
    'Are you a double? The thought of you always floats inside my head.',
    'My love for you cannot be measured with an int, not with a long, and  not even with an array. It is out of bounds and infinite…. ',
    'Let\'s make like Dijkstra\'s and find the shortest path between you and me(:',
    'Fear { display: none; }',
];
